#!/bin/bash

# tarit expanded with the arguments check

# usage: tarit.sh <dirname>
if ! (($#)); then
  tar caf $(basename $(pwd)).$(date +%Y-%m-%d).tar.gz .
  exit
fi

# loop over $@
for d; do
  # if dirname is given, we archive it
  if [[ -d $d ]]; then
    tar caf $(basename $d).$(date +%Y-%m-%d).tar.gz $d
  else
    echo $d does not exist
    continue
  fi
done
